version: "3.9"
services:
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"

  scrapper:
    image: amerkurev/scrapper:latest
    restart: unless-stopped
    volumes:
      - "./user_data:/home/user/user_data"
      # - "./user_scripts:/home/user/user_scripts"

volumes:
  caddy_data:
  caddy_config:
