services:
  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"

  scrapper:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: fizzbuzz2/scrapper:v1.3.0
    restart: unless-stopped
    volumes:
      - "./user_data:/home/user/user_data"
      - "./user_scripts:/home/user/user_scripts"

volumes:
  caddy_data:
  caddy_config:
